name: Test Deploy

on:
  push:
    branches: [ test-action-deploy ]
  
jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/ghst-gg-client/client
        steps:

        - name: Login
          uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
          with:
            project_id: ${{ secrets.GCP_PROJECT }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_SA_KEY }}
